### ISSUE TITLE
Error from numeral package for all kafka-tools commands

### ISSUE THREAD

**Issue by sambaran69** [advertine/kafka-tools#1]
I am getting the following error from most of the kafka-tools commands:

**kafka-topics --create testload p1 r1**
/usr/local/lib/node_modules/kafka-tools/bin/kafka-topics.js:30
numeral.language('pl', {
        ^

TypeError: numeral.language is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/kafka-tools/bin/kafka-topics.js:30:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
sambaran.roy@TA059167MAC kafka $ **kafka-topics -c**
/usr/local/lib/node_modules/kafka-tools/bin/kafka-topics.js:30
numeral.language('pl', {
        ^

TypeError: numeral.language is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/kafka-tools/bin/kafka-topics.js:30:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by royaltm** [comment]
thanks, probably 'cause i didn't care about the dependency version for numeral...
```
"numeral": "*"
```

fixing soon

**Comment by royaltm** [comment]
fixed, should be ok now
